//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admit_Card
    {
        public int School_Code { get; set; }
        public int GuardianID { get; set; }
        public int Roll_Number { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual School School { get; set; }
    }
}
