//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Admit_Card = new HashSet<Admit_Card>();
            this.Examinations = new HashSet<Examination>();
        }
    
        public int Roll_Number { get; set; }
        public int StatusID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> School_Code { get; set; }
        public int GuardianID { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Picture { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public bool Private_Candidate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Admit_Card> Admit_Card { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual Person Person { get; set; }
        public virtual School School { get; set; }
        public virtual Status_2 Status_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
    }
}
