//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSEKDatabaseEntities : DbContext
    {
        public BSEKDatabaseEntities()
            : base("name=BSEKDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Admit_Card> Admit_Cards { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<Guardian> Guardians { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Principle> Principles { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Status_2> Status_2 { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
    }
}
